manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: friggeri
      url-base: https://github.com/friggeri
  projects:
    - name: zmk
      remote: friggeri
      revision: feat/hid-joystick
      import: app/west.yml
    - name: zmk-analog-joystick-driver
      remote: friggeri
      revision: main
    - name: zmk-joystick-listener
      remote: friggeri
      revision: main
  self:
    path: config